/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSubjectRouteImport } from './routes/subjects.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSubjectRoute = SubjectsSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => SubjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marks': typeof MarksRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marks': typeof MarksRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/console': typeof ConsoleRoute
  '/dashboard': typeof DashboardRoute
  '/marks': typeof MarksRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/console'
    | '/dashboard'
    | '/marks'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/subjects'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/console'
    | '/dashboard'
    | '/marks'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/analytics'
    | '/auth'
    | '/calendar'
    | '/console'
    | '/dashboard'
    | '/marks'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/subjects'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ConsoleRoute: typeof ConsoleRoute
  DashboardRoute: typeof DashboardRoute
  MarksRoute: typeof MarksRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TimerRoute: typeof TimerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$subject': {
      id: '/subjects/$subject'
      path: '/$subject'
      fullPath: '/subjects/$subject'
      preLoaderRoute: typeof SubjectsSubjectRouteImport
      parentRoute: typeof SubjectsRoute
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSubjectRoute: typeof SubjectsSubjectRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectRoute: SubjectsSubjectRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ConsoleRoute: ConsoleRoute,
  DashboardRoute: DashboardRoute,
  MarksRoute: MarksRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  TermsRoute: TermsRoute,
  TimerRoute: TimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
