/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AskASeniorRouteImport } from './routes/ask-a-senior'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as OlAlRouteImport } from './routes/ol-al'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PathwayRouteImport } from './routes/pathway'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillLabRouteImport } from './routes/skill-lab'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSubjectRouteImport } from './routes/subjects.$subject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AskASeniorRoute = AskASeniorRouteImport.update({
  id: '/ask-a-senior',
  path: '/ask-a-senior',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const OlAlRoute = OlAlRouteImport.update({
  id: '/ol-al',
  path: '/ol-al',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwayRoute = PathwayRouteImport.update({
  id: '/pathway',
  path: '/pathway',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillLabRoute = SkillLabRouteImport.update({
  id: '/skill-lab',
  path: '/skill-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSubjectRoute = SubjectsSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => SubjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/ask-a-senior': typeof AskASeniorRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/marks': typeof MarksRoute
  '/ol-al': typeof OlAlRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pathway': typeof PathwayRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/skill-lab': typeof SkillLabRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/ask-a-senior': typeof AskASeniorRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/marks': typeof MarksRoute
  '/ol-al': typeof OlAlRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pathway': typeof PathwayRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/skill-lab': typeof SkillLabRoute
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/analytics': typeof AnalyticsRoute
  '/ask-a-senior': typeof AskASeniorRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learn': typeof LearnRoute
  '/marks': typeof MarksRoute
  '/ol-al': typeof OlAlRoute
  '/opportunities': typeof OpportunitiesRoute
  '/pathway': typeof PathwayRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reels': typeof ReelsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/skill-lab': typeof SkillLabRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/terms': typeof TermsRoute
  '/timer': typeof TimerRoute
  '/subjects/$subject': typeof SubjectsSubjectRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/ask-a-senior'
    | '/auth'
    | '/calendar'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/marks'
    | '/ol-al'
    | '/opportunities'
    | '/pathway'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/reels'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/skill-lab'
    | '/subjects'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/ask-a-senior'
    | '/auth'
    | '/calendar'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/marks'
    | '/ol-al'
    | '/opportunities'
    | '/pathway'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/reels'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/skill-lab'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/analytics'
    | '/ask-a-senior'
    | '/auth'
    | '/calendar'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/explore'
    | '/features'
    | '/how-it-works'
    | '/learn'
    | '/marks'
    | '/ol-al'
    | '/opportunities'
    | '/pathway'
    | '/portfolio'
    | '/privacy'
    | '/progress'
    | '/reels'
    | '/reset-password'
    | '/revision'
    | '/settings'
    | '/skill-lab'
    | '/subjects'
    | '/terms'
    | '/timer'
    | '/subjects/$subject'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AskASeniorRoute: typeof AskASeniorRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LearnRoute: typeof LearnRoute
  MarksRoute: typeof MarksRoute
  OlAlRoute: typeof OlAlRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PathwayRoute: typeof PathwayRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ReelsRoute: typeof ReelsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  SkillLabRoute: typeof SkillLabRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TimerRoute: typeof TimerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-a-senior': {
      id: '/ask-a-senior'
      path: '/ask-a-senior'
      fullPath: '/ask-a-senior'
      preLoaderRoute: typeof AskASeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ol-al': {
      id: '/ol-al'
      path: '/ol-al'
      fullPath: '/ol-al'
      preLoaderRoute: typeof OlAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathway': {
      id: '/pathway'
      path: '/pathway'
      fullPath: '/pathway'
      preLoaderRoute: typeof PathwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-lab': {
      id: '/skill-lab'
      path: '/skill-lab'
      fullPath: '/skill-lab'
      preLoaderRoute: typeof SkillLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$subject': {
      id: '/subjects/$subject'
      path: '/$subject'
      fullPath: '/subjects/$subject'
      preLoaderRoute: typeof SubjectsSubjectRouteImport
      parentRoute: typeof SubjectsRoute
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSubjectRoute: typeof SubjectsSubjectRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectRoute: SubjectsSubjectRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AnalyticsRoute: AnalyticsRoute,
  AskASeniorRoute: AskASeniorRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LearnRoute: LearnRoute,
  MarksRoute: MarksRoute,
  OlAlRoute: OlAlRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PathwayRoute: PathwayRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ReelsRoute: ReelsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  SkillLabRoute: SkillLabRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  TermsRoute: TermsRoute,
  TimerRoute: TimerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
